# Generated by Django 4.2.6 on 2023-11-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=64)),
                ('Apellido', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mostrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=64)),
                ('Apellido', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subencargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=64)),
                ('Apellido', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
    ]
