# Generated by Django 4.2.6 on 2023-11-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_rename_timestamp_message_created_at_message_is_read_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
