# Generated by Django 4.2.6 on 2023-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargado',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mostrador',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subencargado',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
